//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG
    {
        public int BlogId { get; set; }
        public string BlogName { get; set; }
        public string BlogComments { get; set; }
        public Nullable<double> Bloglength { get; set; }
        public Nullable<System.DateTime> BlogPublishDate { get; set; }
    }
}
